# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-demoapp-service
  namespace: maksim
  labels:
    app: python-demoapp
spec:
  type: NodePort
  selector:
    app: python-demoapp
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32001